TrabajoHoy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from TrabajoHoy import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    #
    path('aplicacionWeb/', include('aplicacionWeb.urls')),
    path('aplicacionBlog/', include('aplicacionBlog.urls')),
    
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

aplicacionBlog/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import LogoutView
urlpatterns = [
    path('', index, name="home"),
    
    
    path('post/', post, name="post"),
    path('vinculaciones/', vinculacion, name="vinculaciones"),
    
        
    path('buscar_habilidades/', buscarHabilidades, name="buscar_habilidades"),
    path('buscar_habilidades2/', buscarHabilidades2, name="buscar_habilidades2"),
    
    path('buscar_titulo/', buscarTitulo, name="buscar_titulo"),
    path('buscar_titulo2/', buscarTitulo2, name="buscar_titulo2"),
    
    path('buscar_rubro/', buscarRubro, name="buscar_rubro"),
    path('buscar_rubro2/', buscarRubro2, name="buscar_rubro2"),
    
    path('buscar_nombre/', buscarNombre, name="buscar_nombre"),
    path('buscar_nombre2/', buscarNombre2, name="buscar_nombre2"),
    
    path('buscar_trabajador/', buscarTrabajador, name="buscar_trabajador"),
    path('buscar_trabajador2/', buscarTrabajador2, name="buscar_trabajador2"),
    
    
        
    path('recomendaciones/', RecomendacionList.as_view(), name="recomendaciones"),
    path('create_recomendacion/', RecomendacionCreate.as_view(), name="create_recomendacion"),
    path('detail_recomendacion/<int:pk>/', RecomendacionDetail.as_view(), name="detail_recomendaciones"),
    path('update_recomendacion/<int:pk>/', RecomendacionUpdate.as_view(), name="update_recomendaciones"),
    path('delete_recomendacion/<int:pk>/', RecomendacionDelete.as_view(), name="delete_recomendaciones"),
    
    path('trabajo/', TrabajoList.as_view(), name="trabajo"),
    path('create_trabajo/', TrabajoCreate.as_view(), name="create_trabajo"),
    path('detail_trabajo/<int:pk>/', TrabajoDetail.as_view(), name="detail_trabajos"),
    path('delete_trabajo/<int:pk>/', TrabajoDelete.as_view(), name="delete_trabajos"),
    path('update_trabajo/<int:pk>/', TrabajoUpdate.as_view(), name="update_trabajos"),
    
    path('trabajador/', TrabajadorList.as_view(), name="trabajador"),
    path('create_trabajador/', TrabajadorCreate.as_view(), name="create_trabajador"),
    path('detail_trabajador/<int:pk>/', TrabajadorDetail.as_view(), name="detail_trabajadores"),
    path('delete_trabajador/<int:pk>/', TrabajadorDelete.as_view(), name="delete_trabajadores"),
    path('update_trabajador/<int:pk>/', TrabajadorUpdate.as_view(), name="update_trabajadores"),
    
    path('login/', login_request, name="login"),
    path('logout/', LogoutView.as_view(template_name="aplicacionBlog/logout.html"), name="logout"),
    path('register/', register, name="register"),
    
    path('editar_perfil/', editarPerfil, name="editar_perfil"),
    path('agregar_avatar/', agregarAvatar, name="agregar_avatar"),
    ]

aplicacionBlog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


RUBRO_CHOICES = [
    ('Tecnología', 'Tecnología'),
    ('Salud', 'Salud'),
    ('Educación', 'Educación'),
    ('Gastronomía', 'Gastronomía'),
    ('Construcción', 'Construcción'),
    ('Arte y Entretenimiento', 'Arte y Entretenimiento'),
    ('Ventas', 'Ventas'),
    ('Servicios', 'Servicios'),
    ('Pintura', 'Pintura'),
    ('Transporte', 'Transporte'),
    ('Plomeria', 'Plomeria'),
    ('Electricidad', 'Electricidad'),
]

class Trabajo(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField()
    rubro = models.CharField(max_length=50, choices=RUBRO_CHOICES)
    salario_ofrecido = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.titulo

class Trabajador(models.Model):
    nombre = models.CharField(max_length=50)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=20)
    rubro = models.CharField(max_length=50, choices=RUBRO_CHOICES)
    habilidades = models.TextField()

    def __str__(self):
        return self.nombre

class Vinculacion(models.Model):
    trabajo = models.ForeignKey(Trabajo, on_delete=models.CASCADE)
    trabajador = models.ForeignKey(Trabajador, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.trabajo.titulo} - {self.trabajador.nombre}"

class Recomendacion(models.Model):
    trabajador = models.ForeignKey(Trabajador, on_delete=models.CASCADE)
    puntaje = models.PositiveIntegerField(choices=[(i, i) for i in range(1, 11)])
    comentarios = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Recomendación de {self.trabajador.nombre}"


from django.db.models.signals import post_save
from django.dispatch import receiver

@receiver(post_save, sender=Trabajador)
def crear_vinculacion(sender, instance, **kwargs):
    if kwargs.get('created', False):
        # Encuentra un trabajo con el mismo rubro que el trabajador
        trabajo_correspondiente = Trabajo.objects.filter(rubro=instance.rubro).first()

        if trabajo_correspondiente:
            Vinculacion.objects.create(trabajo=trabajo_correspondiente, trabajador=instance)

class Avatar(models.Model):
    imagen = models.ImageField(upload_to="avatares")
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    
    def __str__(self):
        return f"{self.user} [{self.imagen}]"

aplicacionBlog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistroUsuariosForm(UserCreationForm):
    email = forms.EmailField(label="Email Usuario")
    password1= forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2= forms.CharField(label="Confirmar Contraseña", widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k:"" for k in fields}
        


    
class UserEditForm(UserCreationForm):
    email = forms.EmailField(label="Modificar Email")
    password1= forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2= forms.CharField(label="Confirmar Contraseña", widget=forms.PasswordInput)
    first_name= forms.CharField(label="Nombre", max_length=50, required=False)
    last_name = forms.CharField(label="Apellido", max_length=50, required=False)
    
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'password1', 'password2']
        help_texts = {k:"" for k in fields}
        
        
        
class AvatarFormulario(forms.Form):
    imagen = forms.ImageField(required=True)

aplicacionBlog/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.urls import reverse_lazy

from aplicacionBlog.forms import *
from .models import *
from .forms import *
from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import DeleteView
from django.views.generic import UpdateView

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, "aplicacionBlog/base.html")

def post(request):
    return render(request, "aplicacionBlog/post.html")

@login_required
def trabajo(request):
    ctx = {"trabajos": Trabajo.objects.all()}
    return render(request, "aplicacionBlog/trabajos.html", ctx)

@login_required
def trabajadores(request):
    ctx = {"trabajador": Trabajador.objects.all()}
    return render(request, "aplicacionBlog/trabajador.html", ctx)

@login_required
def vinculacion(request):
    ctx = {"vinculaciones": Vinculacion.objects.all()}
    return render(request, "aplicacionBlog/vinculaciones.html", ctx)

@login_required
def recomendaciones(request):
    ctx = {"recomendaciones": Recomendacion.objects.all()}
    return render(request, "aplicacionBlog/recomendaciones.html", ctx)





@login_required
def buscarTitulo(request):
    return render(request, "aplicacionBlog/buscarTitulo.html")

@login_required
def buscarTitulo2(request):
    if request.GET ['titulo']:
        titulo = request.GET['titulo']
        trabajos = Trabajo.objects.filter(titulo__icontains=titulo)
        return render(request, "aplicacionBlog/resultadosTitulos.html", {"titulo": titulo, "trabajos": trabajos})
    return HttpResponse("No fueron ingresados datos")  

@login_required
def buscarRubro(request):
    return render(request, "aplicacionBlog/buscarRubro.html")

@login_required
def buscarRubro2(request):
    if request.GET ['rubro']:
        rubro = request.GET['rubro']
        trabajos = Trabajo.objects.filter(rubro__icontains=rubro)
        return render(request, "aplicacionBlog/resultadosRubros.html", {"rubro": rubro, "trabajos": trabajos})
    return HttpResponse("No fueron ingresados datos")  

@login_required
def buscarNombre(request):
    return render(request, "aplicacionBlog/buscarNombre.html")

@login_required
def buscarNombre2(request):
    if request.GET ['nombre']:
        nombre = request.GET['nombre']
        trabajadores = Trabajador.objects.filter(nombre__icontains=nombre)
        return render(request, "aplicacionBlog/resultadosNombres.html", {"nombre": nombre, "trabajadores": trabajadores})
    return HttpResponse("No fueron ingresados datos")  

@login_required
def buscarHabilidades(request):
    return render(request, "aplicacionBlog/buscarHabilidades.html")

@login_required
def buscarHabilidades2(request):
    if request.GET ['habilidades']:
        habilidades = request.GET['habilidades']
        trabajadores = Trabajador.objects.filter(habilidades__icontains=habilidades)
        return render(request, "aplicacionBlog/resultadosHabilidades.html", {"habilidades": habilidades, "trabajadores": trabajadores})
    return HttpResponse("No fueron ingresados datos") 
  
@login_required
def buscarTrabajador(request):
    return render(request, "aplicacionBlog/buscarTrabajador.html")

@login_required
def buscarTrabajador2(request):
    if request.GET ['trabajador']:
        trabajador = request.GET['trabajador']
        recomendaciones = Recomendacion.objects.filter(trabajador__icontains=trabajador)
        return render(request, "aplicacionBlog/resultadosRecomendaciones.html", {"trabajador": trabajador, "recomendaciones": recomendaciones})
    return HttpResponse("No fueron ingresados datos")  






class RecomendacionList(LoginRequiredMixin, ListView):
    model = Recomendacion
class RecomendacionCreate(LoginRequiredMixin, CreateView):
    model = Recomendacion
    fields = ['trabajador', 'puntaje', 'comentarios']
    success_url = reverse_lazy('recomendaciones')
class RecomendacionDetail(LoginRequiredMixin, DetailView):
    model = Recomendacion
class RecomendacionUpdate(LoginRequiredMixin, UpdateView):
    model = Recomendacion
    fields = ['trabajador', 'puntaje', 'comentarios']
    success_url = reverse_lazy('recomendaciones')
class RecomendacionDelete(LoginRequiredMixin, DeleteView):
    model = Recomendacion
    success_url = reverse_lazy('recomendaciones')
    
        
class TrabajadorList(LoginRequiredMixin, ListView):
    model = Trabajador
class TrabajadorCreate(LoginRequiredMixin, CreateView):
    model = Trabajador
    fields = ['nombre', 'edad', 'telefono', 'rubro', 'habilidades']
    success_url = reverse_lazy('trabajador')
class TrabajadorDetail(LoginRequiredMixin, DetailView):
    model = Trabajador
class TrabajadorUpdate(LoginRequiredMixin, UpdateView):
    model = Trabajador
    fields = ['nombre', 'edad', 'telefono', 'rubro', 'habilidades']
    success_url = reverse_lazy('trabajador')
class TrabajadorDelete(LoginRequiredMixin, DeleteView):
    model = Trabajador
    success_url = reverse_lazy('trabajador')

    
    
class TrabajoList(LoginRequiredMixin, ListView):
    model = Trabajo  
class TrabajoCreate(LoginRequiredMixin, CreateView):
    model = Trabajo
    fields = ['titulo', 'descripcion', 'rubro', 'salario_ofrecido']
    success_url = reverse_lazy('trabajo')  
class TrabajoDetail(LoginRequiredMixin, DetailView):
    model = Trabajo 
class TrabajoUpdate(LoginRequiredMixin, UpdateView):
    model = Trabajo
    fields = ['titulo', 'descripcion', 'rubro', 'salario_ofrecido']
    success_url = reverse_lazy('trabajo')  
class TrabajoDelete(LoginRequiredMixin, DeleteView):
    model = Trabajo 
    success_url = reverse_lazy('trabajo') 
    
    
    
    
def login_request(request):
    if request.method == "POST":
        miForm = AuthenticationForm(request, data=request.POST)
        if miForm.is_valid():
            usuario = miForm.cleaned_data.get('username')
            clave = miForm.cleaned_data.get('password')
            user = authenticate(username=usuario, password=clave)
            if user is not None:
                login(request, user)
                
                try:
                    avatar = Avatar.objects.get(user.id).imagen.url
                except:
                    avatar = '/media/avatares/default.png'
                finally:
                    request.session['avatar'] = avatar
                    
                return render(request, "aplicacionBlog/base.html", {"mensaje":f"Hola {usuario}"})
            else:
                return render(request, "aplicacionBlog/login.html", {"form":miForm, "mensaje": "Datos Invalidos"})
        else:
            return render(request, "aplicacionBlog/login.html", {"form":miForm, "mensaje": "Datos Invalidos"})
        
    miForm = AuthenticationForm()
    
    return render(request, "aplicacionBlog/login.html", {"form":miForm})


def register(request):
    if request.method == 'POST':
        form = RegistroUsuariosForm(request.POST)
        if form.is_valid(): 
            usuario = form.cleaned_data.get('username')
            form.save()
            return render(request, "aplicacionBlog/base.html", {"mensaje":"Usuario Creado"})
    else:
            form = RegistroUsuariosForm()
            
    return render(request, "aplicacionBlog/registro.html", {"form": form})

@login_required
def editarPerfil(request):
    usuario = request.user
    if request.method == "POST":
        form = UserEditForm(request.POST)
        if form.is_valid():
            usuario.email = form.cleaned_data.get('email')
            usuario.password1 = form.cleaned_data.get('password1')
            usuario.password2  = form.cleaned_data.get('password2')
            usuario.first_name = form.cleaned_data.get('first_name')
            usuario.last_name = form.cleaned_data.get('last_name')
            usuario.save()
            return render(request, "aplicacionBlog/base.html", {'mensaje': f"Usuario {usuario.username} actualizado correctamente"})
        else:
            return render(request, "aplicacionBlog/editarPerfil.html", {"form": form})
    else:
        form = UserEditForm(instance=usuario)
    return render(request, "aplicacionBlog/editarPerfil.html", {'form': form, 'Usuario':usuario.username})


# ... your imports and other code ...

@login_required
def agregarAvatar(request):
    if request.method == "POST":
        form = AvatarFormulario(request.POST, request.FILES)
        if form.is_valid():
            u = User.objects.get(username=request.user)
            avatarViejo = Avatar.objects.filter(user=u)
            if len(avatarViejo) > 0:
                avatarViejo[0].delete()

            avatar = Avatar(user=u, imagen=form.cleaned_data['imagen'])
            avatar.save()

            # Store the avatar ID in the session
            imagen = Avatar.objects.get(user=request.user.id).imagen.url
            request.session['avatar'] = imagen

            return render(request, "aplicacionBlog/base.html")

    else:
        form = AvatarFormulario()
        
    return render(request, "aplicacionBlog/agregarAvatar.html", {'form': form})

aplicacionBlog/templates/aplicacionBlog/buscarHabilidades.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buscar Habilidades</title>
</head>
<body>
    <h3 style="font-size: 24px; color: #ff9900; text-transform: uppercase; letter-spacing: 2px;">Buscar una Nueva Oportunidad</h3>
    <form action="/aplicacionBlog/buscar_habilidades2" method="get">
        {% csrf_token %}
        <input type="text" name="habilidades" id="habilidades">
        <input type="submit" value="Buscar">
    </form>
</body>
</html>

aplicacionBlog/templates/aplicacionBlog/buscarNombre.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buscar Nombre</title>
</head>
<body>
    <h3 style="font-size: 24px; color: #ff9900; text-transform: uppercase; letter-spacing: 2px;">Buscar una Nueva Oportunidad</h3>
    <form action="/aplicacionBlog/buscar_nombre2" method="get">
        {% csrf_token %}
        <input type="text" name="nombre" id="nombre">
        <input type="submit" value="Buscar">
    </form>
</body>
</html>

aplicacionBlog/templates/aplicacionBlog/buscarTitulo.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buscar Titulo</title>
</head>
<body>
    <h3 style="font-size: 24px; color: #ff9900; text-transform: uppercase; letter-spacing: 2px;">Buscar una Nueva Oportunidad</h3>
    <form action="/aplicacionBlog/buscar_titulo2" method="get">
        {% csrf_token %}
        <input type="text" name="titulo" id="titulo">
        <input type="submit" value="Buscar">
    </form>
</body>
</html>

aplicacionBlog/templates/aplicacionBlog/logout.html
{% extends 'aplicacionBlog/base.html' %}
{% load static %}

{% block cabecera %}
    <div class="masthead-heading text-uppercase">Registro</div>
{% endblock cabecera %}

{% block contenido %}
<br>
    <h4>
       <p style="color:black" align="center">
          Usted se deslogueo.
       </p>
    </h4>
{% endblock contenido %}

aplicacionBlog/templates/aplicacionBlog/trabajador_detail.html
{% extends 'aplicacionBlog/base.html' %}
{% load static %}

{% block cabecera %}
    <div class="masthead-heading text-uppercase">Listado de trabajadores</div>
{% endblock cabecera %}

{% block contenido %}
<table>
    <tr>
        <td width="200"><h2>Trabajadores: {{ object}}</h2></td>
    </tr>
</table>
    <section class="page-section" id="services">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Trabajadores</h2>
                <h3 class="section-subheading text-muted">"Vini, vidi, vinci"</h3>
            </div>
            <div class="row text-center">
                <!-- Other tags and content here -->
            </div>
        </div>
    </section>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Edad</th>
                <th>Telefono</th>
                <th>Rubro</th>
                <th>Habilidades</th>
            </tr>
        </thead>
        <tbody>
            
                <tr>
                    <td>{{ trabajador.id }}</td>
                    <td>{{ trabajador.nombre }}</td>
                    <td>{{ trabajador.edad }}</td>
                    <td>{{ trabajador.telefono }}</td>
                    <td>{{ trabajador.get_rubro_display }}</td>
                    <td>{{ trabajador.habilidades }}</td>
                    
                </tr>
            
        </tbody>
    </table>
    <a
    href="{% url 'trabajador' %}"
    class="btn btn-danger"
    style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;"
    ><i class= "fa fa-edit fa-sm" title="List Back">Volver</i>
    </a>
{% endblock contenido %}

aplicacionBlog/templates/aplicacionBlog/trabajador_list.html
{% extends 'aplicacionBlog/base.html' %}
{% load static %}

{% block cabecera %}
    <div class="masthead-heading text-uppercase">Listado de trabajadores</div>
{% endblock cabecera %}

{% block contenido %}
<table>
    <tr>
        <td width="200"><h2>Trabajadores</h2></td>
        <td>
            <a 
            href="{% url 'create_trabajador' %}"
            class="btn btn-primary btn-sm"
            ><i class="fa fa-plus fa-lg" title="New Record"> </i>
            </a>
        </td>
    </tr>
</table>
    <section class="page-section" id="services">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Trabajadores</h2>
                <h3 class="section-subheading text-muted">"Vini, vidi, vinci"</h3>
            </div>
            <div class="row text-center">
                <!-- Other tags and content here -->
            </div>
        </div>
    </section>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Edad</th>
                <th>Telefono</th>
                <th>Rubro</th>
                <th>Habilidades</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for trabajador in trabajador_list %}
                <tr>
                    <td>{{ trabajador.id }}</td>
                    <td>{{ trabajador.nombre }}</td>
                    <td>{{ trabajador.edad }}</td>
                    <td>{{ trabajador.telefono }}</td>
                    <td>{{ trabajador.get_rubro_display }}</td>
                    <td>{{ trabajador.habilidades }}</td>
                    <td>
                        <a
                        href="{% url 'detail_trabajadores' trabajador.id %}"
                        class="btn btn-info"
                        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;"
                        ><i class= "fa fa-search fa-sm" title="View Record"></i>
                        </a>
                        <a
                        href="{% url 'update_trabajadores' trabajador.id %}"
                        class="btn btn-primary"
                        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;"
                        ><i class= "fa fa-edit fa-sm" title="Edit Record"></i>
                        </a>
                        <a
                        href="{% url 'delete_trabajadores' trabajador.id %}"
                        class="btn btn-danger"
                        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;"
                        ><i class= "fa fa-trash fa-sm" title="Delete Record"></i>
                        </a>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock contenido %}

aplicacionBlog/templates/aplicacionBlog/trabajo_detail.html
{% extends 'aplicacionBlog/base.html' %}
{% load static %}

{% block cabecera %}
    <div class="masthead-heading text-uppercase">Listado de trabajos</div>
{% endblock cabecera %}

{% block contenido %}
<table>
    <tr>
        <td width="200"><h2>Trabajos: {{ object}}</h2></td>
    </tr>
</table>
    <section class="page-section" id="services">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Trabajos</h2>
                <h3 class="section-subheading text-muted">"Vini, vidi, vinci"</h3>
            </div>
            <div class="row text-center">
                <!-- Other tags and content here -->
            </div>
        </div>
    </section>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Titulo</th>
                <th>Descripcion</th>
                <th>Rubro</th>
                <th>Salario_Ofrecido</th>
            </tr>
        </thead>
        <tbody>
            
                <tr>
                    <td>{{ object.id }}</td>
                    <td>{{ object.titulo }}</td>
                    <td>{{ object.descripcion }}</td>
                    <td>{{ object.get_rubro_display }}</td>
                    <td>{{ object.salario_ofrecido }}</td>
                    <td>
                </tr>
            
        </tbody>
    </table>
    <a
    href="{% url 'trabajo' %}"
    class="btn btn-danger"
    style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;"
    ><i class= "fa fa-trash fa-sm" title="List Back">Volver</i>
    </a>
{% endblock contenido %}

aplicacionBlog/templates/aplicacionBlog/trabajo_list.html
{% extends 'aplicacionBlog/base.html' %}
{% load static %}

{% block cabecera %}
    <div class="masthead-heading text-uppercase">Listado de trabajos</div>
{% endblock cabecera %}

{% block contenido %}
<table>
    <tr>
        <td width="200"><h2>Trabajos</h2></td>
        <td>
            <a 
            href="{% url 'create_trabajo' %}"
            class="btn btn-primary btn-sm"
            ><i class="fa fa-plus fa-lg" title="New Record"> </i>
            </a>
        </td>
    </tr>
</table>
    <section class="page-section" id="services">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Trabajos</h2>
                <h3 class="section-subheading text-muted">"Vini, vidi, vinci"</h3>
            </div>
            <div class="row text-center">
                <!-- Other tags and content here -->
            </div>
        </div>
    </section>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Titulo</th>
                <th>Descripcion</th>
                <th>Rubro</th>
                <th>Salario_Ofrecido</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for trabajo in trabajo_list %}
                <tr>
                    <td>{{ trabajo.id }}</td>
                    <td>{{ trabajo.titulo }}</td>
                    <td>{{ trabajo.descripcion }}</td>
                    <td>{{ trabajo.get_rubro_display }}</td>
                    <td>{{ trabajo.salario_ofrecido }}</td>
                    <td>
                        <a
                        href="{% url 'detail_trabajos' trabajo.id %}"
                        class="btn btn-info"
                        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;"
                        ><i class= "fa fa-search fa-sm" title="View Record"></i>
                        </a>
                        <a
                        href="{% url 'update_trabajos' trabajo.id %}"
                        class="btn btn-primary"
                        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;"
                        ><i class= "fa fa-edit fa-sm" title="Delete Record"></i>
                        </a>
                        <a
                        href="{% url 'delete_trabajos' trabajo.id %}"
                        class="btn btn-danger"
                        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;"
                        ><i class= "fa fa-trash fa-sm" title="Delete Record"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock contenido %}